application: tweetpong
version: 13
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: .*
  script: main.py

error_handlers:
  - file: error.png
    mime_type: image/png

  - error_code: over_quota
    file: overquota.png
    mime_type: image/png

skip_files: |
 ^(.*/)?(
 (.*\.py[co])|
 (\..*)|
 (.*\.xcf)|
 )$
