application: tweetpng
module: default
version: 25
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: .*
  script: main.app

error_handlers:
- file: error.png
  mime_type: image/png

- error_code: over_quota
  file: overquota.png
  mime_type: image/png

skip_files: |
 ^(.*/)?(
 (.*\.py[co])|
 (\..*)|
 (.*\.xcf)|
 )$
