application: tweetpong
version: 5
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: .*
  script: main.py

skip_files: |
 ^(.*/)?(
 (.*\.py[co])|
 (\..*)|
 (.*\.xcf)|
 )$
